import { reactive, computed, watch } from 'vue'

const storedLocale = typeof localStorage !== 'undefined' ? localStorage.getItem('locale') : null
const storedTheme = typeof localStorage !== 'undefined' ? localStorage.getItem('theme') : null

const settings = reactive({
  locale: storedLocale || 'en',
  theme: storedTheme || 'light',
})

const translations = {
  en: {
    navbar: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      gallery: 'Gallery',
      destination: 'Destination',
      contact: 'Contact',
      login: 'Login',
      photos: 'Photos',
      videos: 'Videos',
      northern: 'Northern Province',
      eastern: 'Eastern Province',
      kigali: 'Kigali City',
      western: 'Western Province',
      southern: 'Southern Province',
    },
    footer: {
      title: 'TEMBERA URWANDA',
      description: 'Discover the beauty of the land of thousand hills',
      quickLinks: 'Quick links',
      destination: 'Destination',
      contactUs: 'Contact us',
      goToContact: 'Go to contact page',
      copyright: 'All rights reserved',
    },
    theme: {
      dark: 'Dark Mode',
      light: 'Light Mode',
    },
    language: {
      label: 'Language',
      en: 'English',
      fr: 'Français',
      rw: 'Kinyarwanda',
    },
    home: {
      heroTag: 'Explore Rwanda',
      heroTitle: 'Welcome to Tembera Urwanda',
      heroText: 'Discover the beauty of Rwanda through immersive travel experiences, scenic destinations, wildlife encounters, and cultural tours designed for every explorer.',
      viewServices: 'View Services',
      browseGallery: 'Browse Gallery',
      card1Title: 'Wildlife Adventures',
      card1Text: 'Track mountain gorillas and explore national parks for unforgettable wildlife moments.',
      card2Title: 'Cultural Discovery',
      card2Text: 'Enjoy local crafts, music, and traditions across Rwanda’s provinces.',
      card3Title: 'Scenic Destinations',
      card3Text: 'Visit Kigali, Lake Kivu, Volcanoes, and more with guided tour options.',
    },
    about: {
      heroTag: 'About Tembera Urwanda',
      heroTitle: 'Our mission is to share Rwanda’s beauty with the world.',
      heroText: 'Tembera Urwanda is a travel platform built to connect visitors with Rwanda’s most inspiring landscapes, wildlife adventures, and cultural experiences. We aim to make travel planning simple, safe, and memorable.',
      card1Title: 'Local Expertise',
      card1Text: 'Our team knows Rwanda and builds authentic tours with trusted local guides.',
      card2Title: 'Personalized Trips',
      card2Text: 'Choose from flexible itineraries for family travel, nature lovers, and adventure seekers.',
      card3Title: 'Responsible Travel',
      card3Text: 'We support community tourism and protect Rwanda’s natural heritage.',
    },
    services: {
      heroTag: 'Our Services',
      heroTitle: 'Travel support designed for every Rwanda journey.',
      heroText: 'From guided excursions to custom itineraries, Tembera Urwanda makes it easy to explore Rwanda with comfort, safety, and unforgettable memories.',
      exploreGallery: 'Explore Gallery',
      contactUs: 'Contact Us',
      guidedToursTitle: 'Guided Tours',
      guidedToursText: 'Expert-led tours across Rwanda, from gorilla treks to city highlights.',
      wildlifeSafarisTitle: 'Wildlife Safaris',
      wildlifeSafarisText: 'Visit national parks and discover Rwanda’s unique wildlife habitats.',
      culturalExperiencesTitle: 'Cultural Experiences',
      culturalExperiencesText: 'Enjoy village visits, craft markets, and cultural shows.',
      transportationTitle: 'Transportation',
      transportationText: 'Comfortable transfers, private cars, and airport pickups.',
      accommodationTitle: 'Accommodation',
      accommodationText: 'Book hotels, lodges, or eco-friendly stays suited to your trip.',
      customItinerariesTitle: 'Custom Itineraries',
      customItinerariesText: 'Tailored planning for families, honeymooners, and adventure seekers.',
      highlight1Title: 'Book with Confidence',
      highlight1Text: 'Flexible booking policies, local support, and trusted guides ensure a smooth trip.',
      highlight2Title: 'Expert Local Guides',
      highlight2Text: 'Our guides are experienced and knowledgeable about Rwanda’s nature and culture.',
      highlight3Title: 'Tailored Planning',
      highlight3Text: 'We customize each itinerary to match your travel pace, interests, and budget.',
    },
    contact: {
      emailTitle: 'Email',
      phoneTitle: 'Contact Number',
      addressTitle: 'Address',
      supportHeading: 'Contact Support',
      supportText: 'Reach out for booking questions, itinerary planning, or travel support. We reply fast during business hours.',
    },
    login: {
      heroTag: 'Member Login',
      heroTitle: 'Sign in to your account',
      heroText: 'Access your travel dashboard, bookings, and support options.',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      signIn: 'Sign In',
      newHere: 'New here?',
      createAccount: 'Create an account',
      fillAllFields: 'Please complete all fields.',
    },
    register: {
      title: 'Register',
      heroText: 'Create an account to start planning your Rwanda travel experience.',
      fullName: 'Full Name',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      submit: 'Create Account',
      already: 'Already have an account?',
      signIn: 'Sign in',
      fillAllFields: 'Please complete all fields.',
      passwordMismatch: 'Passwords do not match.',
      createdMessage: 'Account created successfully for {name}.',
    },
    dashboard: {
      welcomeTag: 'Dashboard',
      title: 'Welcome to Your Dashboard',
      subtitle: 'Manage your bookings, view activity, and explore your travel dashboard.',
      status: 'Account status',
      active: 'Active',
      stats: {
        visits: 'Profile Visits',
        visitsLabel: 'Last 30 days',
        bookings: 'Bookings',
        bookingsLabel: 'Confirmed trips',
        reviews: 'Review Score',
        reviewsLabel: 'Customer satisfaction',
      },
      recentTitle: 'Recent activity',
      recentSubtitle: 'Your latest travel updates and booking insights.',
      recentCard1: {
        title: 'Latest Booking',
        text: 'View your latest travel itinerary and booking details in one place.',
      },
      recentCard2: {
        title: 'Travel Insights',
        text: 'See recommendations and suggestions based on your recent searches.',
      },
    },
  },
  fr: {
    navbar: {
      home: 'Accueil',
      about: 'À propos',
      services: 'Services',
      gallery: 'Galerie',
      destination: 'Destination',
      contact: 'Contact',
      login: 'Connexion',
      photos: 'Photos',
      videos: 'Vidéos',
      northern: 'Province Nord',
      eastern: 'Province Est',
      kigali: 'Ville de Kigali',
      western: 'Province Ouest',
      southern: 'Province Sud',
    },
    footer: {
      title: 'TEMBERA URWANDA',
      description: 'Découvrez la beauté de la terre des mille collines',
      quickLinks: 'Liens rapides',
      destination: 'Destination',
      contactUs: 'Contactez-nous',
      goToContact: 'Aller à la page de contact',
      copyright: 'Tous droits réservés',
    },
    theme: {
      dark: 'Mode sombre',
      light: 'Mode clair',
    },
    language: {
      label: 'Langue',
      en: 'Anglais',
      fr: 'Français',
      rw: 'Kinyarwanda',
    },
    home: {
      heroTag: 'Explorez le Rwanda',
      heroTitle: 'Bienvenue à Tembera Urwanda',
      heroText: 'Découvrez la beauté du Rwanda à travers des expériences de voyage immersives, des destinations pittoresques, des rencontres avec la faune et des visites culturelles conçues pour chaque explorateur.',
      viewServices: 'Voir les services',
      browseGallery: 'Parcourir la galerie',
      card1Title: 'Aventures fauniques',
      card1Text: 'Suivez des gorilles de montagne et explorez les parcs nationaux pour des moments inoubliables.',
      card2Title: 'Découverte culturelle',
      card2Text: 'Profitez de l’artisanat local, de la musique et des traditions à travers les provinces du Rwanda.',
      card3Title: 'Destinations pittoresques',
      card3Text: 'Visitez Kigali, le lac Kivu, les volcans et plus encore avec des options de visite guidée.',
    },
    about: {
      heroTag: 'À propos de Tembera Urwanda',
      heroTitle: 'Notre mission est de partager la beauté du Rwanda avec le monde.',
      heroText: 'Tembera Urwanda est une plateforme de voyage conçue pour connecter les visiteurs aux paysages les plus inspirants du Rwanda, aux aventures de la faune et aux expériences culturelles. Nous visons à simplifier la planification de voyage, à la rendre sécurisée et mémorable.',
      card1Title: 'Expertise locale',
      card1Text: 'Notre équipe connaît le Rwanda et construit des circuits authentiques avec des guides locaux de confiance.',
      card2Title: 'Voyages personnalisés',
      card2Text: 'Choisissez parmi des itinéraires flexibles pour les voyages en famille, les amoureux de la nature et les aventuriers.',
      card3Title: 'Voyage responsable',
      card3Text: 'Nous soutenons le tourisme communautaire et protégeons le patrimoine naturel du Rwanda.',
    },
    services: {
      heroTag: 'Nos services',
      heroTitle: 'Support de voyage conçu pour chaque voyage au Rwanda.',
      heroText: 'Des excursions guidées aux itinéraires personnalisés, Tembera Urwanda facilite l’exploration du Rwanda avec confort, sécurité et souvenirs inoubliables.',
      exploreGallery: 'Explorer la galerie',
      contactUs: 'Contactez-nous',
      guidedToursTitle: 'Circuits guidés',
      guidedToursText: 'Des visites dirigées par des experts à travers le Rwanda, des treks gorilles aux points forts de la ville.',
      wildlifeSafarisTitle: 'Safaris fauniques',
      wildlifeSafarisText: 'Visitez les parcs nationaux et découvrez les habitats fauniques uniques du Rwanda.',
      culturalExperiencesTitle: 'Expériences culturelles',
      culturalExperiencesText: 'Profitez des visites de villages, des marchés artisanaux et des spectacles culturels.',
      transportationTitle: 'Transport',
      transportationText: 'Transferts confortables, voitures privées et prises en charge à l’aéroport.',
      accommodationTitle: 'Hébergement',
      accommodationText: 'Réservez des hôtels, lodges ou séjours éco-responsables adaptés à votre voyage.',
      customItinerariesTitle: 'Itinéraires personnalisés',
      customItinerariesText: 'Planification sur mesure pour les familles, les lunes de miel et les aventuriers.',
      highlight1Title: 'Réservez en toute confiance',
      highlight1Text: 'Politiques de réservation flexibles, assistance locale et guides de confiance pour garantir un voyage fluide.',
      highlight2Title: 'Guides locaux experts',
      highlight2Text: 'Nos guides sont expérimentés et connaissent bien la nature et la culture du Rwanda.',
      highlight3Title: 'Planification sur mesure',
      highlight3Text: 'Nous personnalisons chaque itinéraire selon votre rythme, vos centres d’intérêt et votre budget.',
    },
    contact: {
      emailTitle: 'Email',
      phoneTitle: 'Numéro de contact',
      addressTitle: 'Adresse',
      supportHeading: 'Support client',
      supportText: 'Contactez-nous pour des questions de réservation, la planification d’itinéraire ou l’assistance de voyage. Nous répondons rapidement pendant les heures ouvrables.',
    },
    login: {
      heroTag: 'Connexion membre',
      heroTitle: 'Connectez-vous à votre compte',
      heroText: 'Accédez à votre tableau de bord de voyage, à vos réservations et à vos options de support.',
      emailLabel: 'Email',
      passwordLabel: 'Mot de passe',
      signIn: 'Se connecter',
      newHere: 'Nouveau ici ?',
      createAccount: 'Créer un compte',
      fillAllFields: 'Veuillez remplir tous les champs.',
    },
    register: {
      title: 'Inscription',
      heroText: 'Créez un compte pour commencer à planifier votre expérience de voyage au Rwanda.',
      fullName: 'Nom complet',
      email: 'Email',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      submit: 'Créer un compte',
      already: 'Vous avez déjà un compte ?',
      signIn: 'Se connecter',
      fillAllFields: 'Veuillez remplir tous les champs.',
      passwordMismatch: 'Les mots de passe ne correspondent pas.',
      createdMessage: 'Compte créé avec succès pour {name}.',
    },
    dashboard: {
      welcomeTag: 'Tableau de bord',
      title: 'Bienvenue sur votre tableau de bord',
      subtitle: 'Gérez vos réservations, consultez votre activité et explorez votre espace de voyage.',
      status: 'Statut du compte',
      active: 'Actif',
      stats: {
        visits: 'Visites du profil',
        visitsLabel: '30 derniers jours',
        bookings: 'Réservations',
        bookingsLabel: 'Voyages confirmés',
        reviews: 'Note',
        reviewsLabel: 'Satisfaction client',
      },
      recentTitle: 'Activité récente',
      recentSubtitle: 'Vos dernières mises à jour de voyage et informations de réservation.',
      recentCard1: {
        title: 'Dernière réservation',
        text: 'Consultez votre dernier itinéraire de voyage et les détails de réservation au même endroit.',
      },
      recentCard2: {
        title: 'Aperçu du voyage',
        text: 'Découvrez des recommandations et suggestions basées sur vos recherches récentes.',
      },
    },
  },
  rw: {
    navbar: {
      home: 'Ahabanza',
      about: 'Ibyerekeye',
      services: 'Serivisi',
      gallery: 'Gallery',
      destination: 'Aho',
      contact: 'Twandikire',
      login: 'Injira',
      photos: 'Amafoto',
      videos: 'Videwo',
      northern: 'Amajyaruguru',
      eastern: 'Iburasirazuba',
      kigali: 'Umujyi wa Kigali',
      western: 'Uburengerazuba',
      southern: 'Amajyepfo',
    },
    footer: {
      title: 'TEMBERA URWANDA',
      description: 'Menya ubwiza bw’ahitwa u Rwanda rw’imisozi igihumbi',
      quickLinks: 'Ibyihuse',
      destination: 'Aho',
      contactUs: 'Twandikire',
      goToContact: 'Jya kuri paji y’itumanaho',
      copyright: 'Uburenganzira bwose burabitswe',
    },
    theme: {
      dark: 'Umukara',
      light: 'Ubururu',
    },
    language: {
      label: 'Ururimi',
      en: 'Icyongereza',
      fr: 'Igifaransa',
      rw: 'Ikinyarwanda',
    },
    home: {
      heroTag: 'Sura u Rwanda',
      heroTitle: 'Murakaza neza muri Tembera Urwanda',
      heroText: 'Menya ubwiza bw’u Rwanda binyuze mu ngendo z’ubukerarugendo, ahantu nyaburanga, guhura n’inyamaswa n’imyidagaduro y’umuco byateguwe ku mukozi wese.',
      viewServices: 'Reba Serivisi',
      browseGallery: 'Reba Gallery',
      card1Title: 'Ingendo z’inyamaswa',
      card1Text: 'Kurikirana ingagi zo mu misozi no gusura pariki za kamere ku byishimo bitazibagirana.',
      card2Title: 'Kumenya umuco',
      card2Text: 'Jya ubona ubukorikori, umuziki n’imigenzo mu turere twose tw’u Rwanda.',
      card3Title: 'Ahantu nyaburanga',
      card3Text: 'Sura Kigali, Kivu, imisozi ya Volcans n’ibindi hamwe n’inzira ziyobowe.',
    },
    about: {
      heroTag: 'Ibyerekeye Tembera Urwanda',
      heroTitle: 'Intego yacu ni gusangiza isi ubwiza bw’u Rwanda.',
      heroText: 'Tembera Urwanda ni urubuga rw’ubukerarugendo rugamije guhuza abashyitsi n’ibyiza by’u Rwanda, ingendo z’inyamaswa, n’ibikorwa by’umuco. Intego yacu ni koroshya gutegura urugendo, tukarurinda kandi tukarwibuka.',
      card1Title: 'Ubumenyi bw’aho',
      card1Text: 'Itsinda ryacu rizwi u Rwanda kandi rikora ingendo z’ukuri hamwe n’abayobozi b’aho bizewe.',
      card2Title: 'Ingendo zihariye',
      card2Text: 'Hitamo gahunda zihinduka zikwiriye ingendo z’umuryango, abakunda kamere, n’abashaka ubundi buryo.',
      card3Title: 'Ubugwaneza mu rugendo',
      card3Text: 'Dushyigikira ubukerarugendo bw’abaturage kandi turinda umutungo kamere w’u Rwanda.',
    },
    services: {
      heroTag: 'Serivisi zacu',
      heroTitle: 'Inkunga y’urugendo yateguwe kuri buri rugendo mu Rwanda.',
      heroText: 'Uhereye ku ngendo ziyobowe kugeza ku ngendo zihariye, Tembera Urwanda iroroshya gusura u Rwanda mu buryo bwiza, bwizewe kandi butazibagirana.',
      exploreGallery: 'Reba Gallery',
      contactUs: 'Twandikire',
      guidedToursTitle: 'Ingendo ziyobowe',
      guidedToursText: 'Ingendo ziyobowe n’inzobere mu Rwanda, kuva ku ngendo z’ingagi kugeza ku byiza by’umujyi.',
      wildlifeSafarisTitle: 'Safari z’inyamaswa',
      wildlifeSafarisText: 'Sura pariki za kamere urebe aho inyamaswa z’u Rwanda ziba.',
      culturalExperiencesTitle: 'Ubumenyi bw’umuco',
      culturalExperiencesText: 'Jya usura imijyi, amasoko y’ubukorikori n’ibirori by’umuco.',
      transportationTitle: 'Ubwikorezi',
      transportationText: 'Kohereza neza, imodoka za mbere, no kuzana ku kibuga cy’indege.',
      accommodationTitle: 'Aho kurara',
      accommodationText: 'Bika amahoteli, amazu y’abashyitsi cyangwa aho kurara hatangiza ibidukikije bigendanye n’urugendo rwawe.',
      customItinerariesTitle: 'Gahunda zihariye',
      customItinerariesText: 'Gutegura ku buryo buhuye n’imiryango, abakundira ubukwe n’abashaka ubukerarugendo.',
      highlight1Title: 'Bika wizeye',
      highlight1Text: 'Amategeko y’igihe cyose, inkunga y’aho, n’abayobozi bizewe bituma urugendo ruhita.',
      highlight2Title: 'Abayobozi b’inzobere b’aho',
      highlight2Text: 'Abayobozi bacu bafite uburambe kandi bazi neza kamere n’umuco w’u Rwanda.',
      highlight3Title: 'Gutegura ku gipimo cyawe',
      highlight3Text: 'Dutunganya buri gahunda bijyanye n’umuvuduko wawe, ibyo ukunda, n’ingengo y’imari yawe.',
    },
    contact: {
      emailTitle: 'Email',
      phoneTitle: 'Nomero y’itumanaho',
      addressTitle: 'Aderesi',
      supportHeading: 'Inkunga y’itumanaho',
      supportText: 'Twandikire ku bibazo by’akazi, gutegura gahunda cyangwa inkunga y’urugendo. Dusubiza vuba mu masaha y’akazi.',
    },
    login: {
      heroTag: 'Kwinjira ku bagize',
      heroTitle: 'Injira kuri konti yawe',
      heroText: 'Jya kuri dashboard y’urugendo rwawe, imyirondoro yawe n’amahirwe y’inkunga.',
      emailLabel: 'Email',
      passwordLabel: 'Ijambo ry’ibanga',
      signIn: 'Injira',
      newHere: 'Uri mushya hano?',
      createAccount: 'Hanga konti',
      fillAllFields: 'Nyamuneka wuzuza imirima yose.',
    },
    register: {
      title: 'Kwiyandikisha',
      heroText: 'Hanga konti kugira ngo utangire gutegura urugendo rwawe mu Rwanda.',
      fullName: 'Amazina yose',
      email: 'Email',
      password: 'Ijambo ry’ibanga',
      confirmPassword: 'Emeza ijambo ry’ibanga',
      submit: 'Hanga konti',
      already: 'Usanzwe ufite konti?',
      signIn: 'Injira',
      fillAllFields: 'Nyamuneka wuzuza imirima yose.',
      passwordMismatch: 'Amajambo y’ibanga ntahuje.',
      createdMessage: 'Konti yaremwe neza kuri {name}.',
    },
    dashboard: {
      welcomeTag: 'Dashboard',
      title: 'Murakaza neza kuri dashboard yawe',
      subtitle: 'Genza ibyifuzo byawe by’ingendo, urebe ibikorwa kandi usure dashboard yawe.',
      status: 'Imiterere ya konti',
      active: 'Iriho',
      stats: {
        visits: 'Abasuye porofaili',
        visitsLabel: 'Iminsi 30 ishize',
        bookings: 'Amabookinga',
        bookingsLabel: 'Inzira zemejwe',
        reviews: 'Inyito y’amanota',
        reviewsLabel: 'Ibyishimo by’abakiriya',
      },
      recentTitle: 'Ibikorwa bishya',
      recentSubtitle: 'Amakuru mashya y’ingendo zawe n’ibyerekeye ibibazo byo kubika.',
      recentCard1: {
        title: 'Icyemezo cya nyuma',
        text: 'Reba gahunda yawe ya vuba n’ibyerekeye ubukerarugendo bwawe ahantu hamwe.',
      },
      recentCard2: {
        title: 'Ibyerekeye ingendo',
        text: 'Reba inama n’ibitekerezo bishingiye ku byo wasuzumye vuba.',
      },
    },
  },
}

const t = (path) => {
  const localeData = translations[settings.locale] || translations.en
  return path.split('.').reduce((value, key) => value?.[key], localeData) ?? path
}

const toggleTheme = () => {
  settings.theme = settings.theme === 'dark' ? 'light' : 'dark'
}

const setLocale = (locale) => {
  if (translations[locale]) {
    settings.locale = locale
  }
}

watch(
  () => settings.theme,
  (value) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('theme', value)
    }
  },
  { immediate: true },
)

watch(
  () => settings.locale,
  (value) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('locale', value)
    }
  },
  { immediate: true },
)

export function useSettings() {
  return {
    settings,
    t,
    toggleTheme,
    setLocale,
  }
}
